spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jooleapp
    username: root
    password: abc12345
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    database: mysql
    show-sql: true